### ISSUE TITLE
Adding Logging to the system

### ISSUE THREAD

**Issue by RiteshKSingh1709** [Shubham8287/flash#17]
- Using logger Factory, create logging object it can file logger or console logger based on the config.
- This will help in debug in prod issue(thinking about future :-p ) 
- Logging can be done at start of method at some important events inside method, at the time of exception and might be at leaving the method (for starting)

**Comment by Shubham8287** [comment]
Other usecase - We need extreme logging for transparency, so user should be able to how things are working under the hood and learn from them.

**Comment by Shubham8287** [comment]
We need a way to find delta accurately to know how particular function is performing in server side.

**Comment by RiteshKSingh1709** [comment]
You mean to say timediff for executing a method ?

**Comment by RiteshKSingh1709** [comment]
taking this up.

**Comment by Shubham8287** [comment]
yep, timediff.
In long term, we will be measuring almost every measurable thing. time taken by chosen DS, storage, middle ware, load balancer delay. Which will generate lot of logs, then we need to way to clean logs as per requirement like - show log from network's perspective, or delay due to particular algo. Also, we need to make sure excessive logging is not consuming server resources.  So logging is crucial in long term, We can use something like sidecar for it - https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar or we can go with simple logging and evolve it with time.

**Comment by RiteshKSingh1709** [comment]
There are multiple options to choose logging framework. I have researched a bit found the in-build go log library can be used, there is one more found which can be used in our case https://github.com/sirupsen/logrus. 

@Shubham8287  Let me know your thoughts

**Comment by Shubham8287** [comment]
picking this up as we need this functionality urgently to start testing

**Comment by Shubham8287** [comment]
Logrus is standard, we can go with it

**Comment by Shubham8287** [comment]
https://sirupsen.com/metrics
